version: "3"
services:
  spark-master:
    image: capacman/spark-master:3.2.1_2.12
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./data/small:/data
      - ./app:/app
    environment:
      - "SPARK_LOCAL_IP=spark-master"
  spark-worker:
    image: capacman/spark-worker:3.2.1_2.12
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=4G
      - SPARK_DRIVER_MEMORY=512m
      - SPARK_EXECUTOR_MEMORY=512m
    volumes:
      - ./data/small:/data
      - ./app:/app
  postgres:
    image: postgres:11-bullseye
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - "POSTGRES_PASSWORD=metastore"
      - "POSTGRES_USER=metastore"
  metastore:
    image: capacman/hive:2.3.9
    depends_on:
      - postgres
    volumes:
      - ./data/small:/data
      - ./app:/app
